---
# plugin by jhampt and JGYTVevo #
# i do custom plugins you can contact me on discord #
# you can contact me in the needs of suggestions to this plugin #
# or if you would like to purchase a custom plugin from me #
# my disocrd server: "Not Done" #
# my discord name: jhampt#0592 #
...
